### ISSUE TITLE
Example related migration in readme file

### ISSUE THREAD

**Issue by tskupinski** [pienkowb/active_record-events#1] opened 2019-04-26 14:44 UTC
It would be nice to have example migration required to use model event presented in readme file.

**Comment by pienkowb** [comment] 2019-07-07 19:03
The example should also cover the case when there's no object defined (which is more common). 

Ideally, there would be a Rails generator responsible for generating a migration and declaring an event in the corresponding model, which would be invoked in the following way:

```ruby
rails generate active_record:event task complete
```

The name of an object would need to be passed as a parameter.

**Comment by pienkowb** [comment] 2019-09-21 16:01
Duplicate of #2

**Closed by pienkowb** 2019-09-21 16:01 UTC
